user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    sendfile on;
    keepalive_timeout 65;

    upstream backend_api {
        server backend:5000;
    }

    upstream frontend_app {
        server frontend:3000;
    }

    # Redirect HTTP -> HTTPS
    server {
        listen 80;
        server_name aarchtou.me www.aarchtou.me;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name aarchtou.me www.aarchtou.me;

        ssl_certificate /etc/ssl/certs/fullchain.pem;
        ssl_certificate_key /etc/ssl/private/privkey.pem;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://backend:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
